### ISSUE TITLE
Cite callout

### ISSUE THREAD

**Issue by dubefab** [tcmmichaelb139/obsidian-tokyonight#11]
I use the "cite" callout differently from "quote," and both are configured together in the theme. 

Is there a way to avoid having to fix this with every update? I use the following callout edit to set my preferred color and icon:

```css
/* callouts */
.callout[data-callout="quote"] {
    background-color: rgba(var(--bg_highlight_dark_x), 0.5);
}

.callout[data-callout="cite"] {
    background-color: rgba(87, 61, 132, 0.5);
}
```
